# Development docker-compose configuration
# Lighter setup for development and testing
# Use: docker-compose -f docker-compose.dev.yml up

version: '3.8'

services:
  # Single node for development
  node:
    build:
      context: .
      target: node
    container_name: dev-node
    ports:
      - "9000:9000"
    volumes:
      - dev-node-data:/data
      # Mount source code for live reload (if needed)
      # - ./lib:/app/lib:ro
    command: ["--port", "9000", "--blockchain-file", "/data/blockchain.cbor"]
    networks:
      - dev-net
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1

  # Single miner for development
  miner:
    build:
      context: .
      target: miner
    container_name: dev-miner
    volumes:
      - dev-miner-keys:/keys
    command:
      - "--address"
      - "node:9000"
      - "--public-key-file"
      - "/keys/miner.pub.pem"
    networks:
      - dev-net
    depends_on:
      - node
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1

  # Utilities
  utils:
    build:
      context: .
      target: utilities
    container_name: dev-utils
    volumes:
      - dev-miner-keys:/keys
      - dev-node-data:/data
    networks:
      - dev-net
    profiles:
      - utils
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

networks:
  dev-net:
    driver: bridge

volumes:
  dev-node-data:
  dev-miner-keys:

